Object.defineProperty(this, "WebGLRenderingContext", {
    value: function WebGLRenderingContext() {
        rsvm.throwErrorNew("WebGLRenderingContext");
    }
}); rsvm.safefunction(WebGLRenderingContext);

Object.defineProperties(WebGLRenderingContext.prototype, {
    [Symbol.toStringTag]: {
        value: "WebGLRenderingContext", configurable: true
    }
});

WebGLRenderingContext.prototype.DEPTH_BUFFER_BIT = WebGLRenderingContext.DEPTH_BUFFER_BIT = 256;
WebGLRenderingContext.prototype.STENCIL_BUFFER_BIT = WebGLRenderingContext.STENCIL_BUFFER_BIT = 1024;
WebGLRenderingContext.prototype.COLOR_BUFFER_BIT = WebGLRenderingContext.COLOR_BUFFER_BIT = 16384;
WebGLRenderingContext.prototype.POINTS = WebGLRenderingContext.POINTS = 0;
WebGLRenderingContext.prototype.LINES = WebGLRenderingContext.LINES = 1;
WebGLRenderingContext.prototype.LINE_LOOP = WebGLRenderingContext.LINE_LOOP = 2;
WebGLRenderingContext.prototype.LINE_STRIP = WebGLRenderingContext.LINE_STRIP = 3;
WebGLRenderingContext.prototype.TRIANGLES = WebGLRenderingContext.TRIANGLES = 4;
WebGLRenderingContext.prototype.TRIANGLE_STRIP = WebGLRenderingContext.TRIANGLE_STRIP = 5;
WebGLRenderingContext.prototype.TRIANGLE_FAN = WebGLRenderingContext.TRIANGLE_FAN = 6;
WebGLRenderingContext.prototype.ZERO = WebGLRenderingContext.ZERO = 0;
WebGLRenderingContext.prototype.ONE = WebGLRenderingContext.ONE = 1;
WebGLRenderingContext.prototype.SRC_COLOR = WebGLRenderingContext.SRC_COLOR = 768;
WebGLRenderingContext.prototype.ONE_MINUS_SRC_COLOR = WebGLRenderingContext.ONE_MINUS_SRC_COLOR = 769;
WebGLRenderingContext.prototype.SRC_ALPHA = WebGLRenderingContext.SRC_ALPHA = 770;
WebGLRenderingContext.prototype.ONE_MINUS_SRC_ALPHA = WebGLRenderingContext.ONE_MINUS_SRC_ALPHA = 771;
WebGLRenderingContext.prototype.DST_ALPHA = WebGLRenderingContext.DST_ALPHA = 772;
WebGLRenderingContext.prototype.ONE_MINUS_DST_ALPHA = WebGLRenderingContext.ONE_MINUS_DST_ALPHA = 773;
WebGLRenderingContext.prototype.DST_COLOR = WebGLRenderingContext.DST_COLOR = 774;
WebGLRenderingContext.prototype.ONE_MINUS_DST_COLOR = WebGLRenderingContext.ONE_MINUS_DST_COLOR = 775;
WebGLRenderingContext.prototype.SRC_ALPHA_SATURATE = WebGLRenderingContext.SRC_ALPHA_SATURATE = 776;
WebGLRenderingContext.prototype.FUNC_ADD = WebGLRenderingContext.FUNC_ADD = 32774;
WebGLRenderingContext.prototype.BLEND_EQUATION = WebGLRenderingContext.BLEND_EQUATION = 32777;
WebGLRenderingContext.prototype.BLEND_EQUATION_RGB = WebGLRenderingContext.BLEND_EQUATION_RGB = 32777;
WebGLRenderingContext.prototype.BLEND_EQUATION_ALPHA = WebGLRenderingContext.BLEND_EQUATION_ALPHA = 34877;
WebGLRenderingContext.prototype.FUNC_SUBTRACT = WebGLRenderingContext.FUNC_SUBTRACT = 32778;
WebGLRenderingContext.prototype.FUNC_REVERSE_SUBTRACT = WebGLRenderingContext.FUNC_REVERSE_SUBTRACT = 32779;
WebGLRenderingContext.prototype.BLEND_DST_RGB = WebGLRenderingContext.BLEND_DST_RGB = 32968;
WebGLRenderingContext.prototype.BLEND_SRC_RGB = WebGLRenderingContext.BLEND_SRC_RGB = 32969;
WebGLRenderingContext.prototype.BLEND_DST_ALPHA = WebGLRenderingContext.BLEND_DST_ALPHA = 32970;
WebGLRenderingContext.prototype.BLEND_SRC_ALPHA = WebGLRenderingContext.BLEND_SRC_ALPHA = 32971;
WebGLRenderingContext.prototype.CONSTANT_COLOR = WebGLRenderingContext.CONSTANT_COLOR = 32769;
WebGLRenderingContext.prototype.ONE_MINUS_CONSTANT_COLOR = WebGLRenderingContext.ONE_MINUS_CONSTANT_COLOR = 32770;
WebGLRenderingContext.prototype.CONSTANT_ALPHA = WebGLRenderingContext.CONSTANT_ALPHA = 32771;
WebGLRenderingContext.prototype.ONE_MINUS_CONSTANT_ALPHA = WebGLRenderingContext.ONE_MINUS_CONSTANT_ALPHA = 32772;
WebGLRenderingContext.prototype.BLEND_COLOR = WebGLRenderingContext.BLEND_COLOR = 32773;
WebGLRenderingContext.prototype.ARRAY_BUFFER = WebGLRenderingContext.ARRAY_BUFFER = 34962;
WebGLRenderingContext.prototype.ELEMENT_ARRAY_BUFFER = WebGLRenderingContext.ELEMENT_ARRAY_BUFFER = 34963;
WebGLRenderingContext.prototype.ARRAY_BUFFER_BINDING = WebGLRenderingContext.ARRAY_BUFFER_BINDING = 34964;
WebGLRenderingContext.prototype.ELEMENT_ARRAY_BUFFER_BINDING = WebGLRenderingContext.ELEMENT_ARRAY_BUFFER_BINDING = 34965;
WebGLRenderingContext.prototype.STREAM_DRAW = WebGLRenderingContext.STREAM_DRAW = 35040;
WebGLRenderingContext.prototype.STATIC_DRAW = WebGLRenderingContext.STATIC_DRAW = 35044;
WebGLRenderingContext.prototype.DYNAMIC_DRAW = WebGLRenderingContext.DYNAMIC_DRAW = 35048;
WebGLRenderingContext.prototype.BUFFER_SIZE = WebGLRenderingContext.BUFFER_SIZE = 34660;
WebGLRenderingContext.prototype.BUFFER_USAGE = WebGLRenderingContext.BUFFER_USAGE = 34661;
WebGLRenderingContext.prototype.CURRENT_VERTEX_ATTRIB = WebGLRenderingContext.CURRENT_VERTEX_ATTRIB = 34342;
WebGLRenderingContext.prototype.FRONT = WebGLRenderingContext.FRONT = 1028;
WebGLRenderingContext.prototype.BACK = WebGLRenderingContext.BACK = 1029;
WebGLRenderingContext.prototype.FRONT_AND_BACK = WebGLRenderingContext.FRONT_AND_BACK = 1032;
WebGLRenderingContext.prototype.TEXTURE_2D = WebGLRenderingContext.TEXTURE_2D = 3553;
WebGLRenderingContext.prototype.CULL_FACE = WebGLRenderingContext.CULL_FACE = 2884;
WebGLRenderingContext.prototype.BLEND = WebGLRenderingContext.BLEND = 3042;
WebGLRenderingContext.prototype.DITHER = WebGLRenderingContext.DITHER = 3024;
WebGLRenderingContext.prototype.STENCIL_TEST = WebGLRenderingContext.STENCIL_TEST = 2960;
WebGLRenderingContext.prototype.DEPTH_TEST = WebGLRenderingContext.DEPTH_TEST = 2929;
WebGLRenderingContext.prototype.SCISSOR_TEST = WebGLRenderingContext.SCISSOR_TEST = 3089;
WebGLRenderingContext.prototype.POLYGON_OFFSET_FILL = WebGLRenderingContext.POLYGON_OFFSET_FILL = 32823;
WebGLRenderingContext.prototype.SAMPLE_ALPHA_TO_COVERAGE = WebGLRenderingContext.SAMPLE_ALPHA_TO_COVERAGE = 32926;
WebGLRenderingContext.prototype.SAMPLE_COVERAGE = WebGLRenderingContext.SAMPLE_COVERAGE = 32928;
WebGLRenderingContext.prototype.NO_ERROR = WebGLRenderingContext.NO_ERROR = 0;
WebGLRenderingContext.prototype.INVALID_ENUM = WebGLRenderingContext.INVALID_ENUM = 1280;
WebGLRenderingContext.prototype.INVALID_VALUE = WebGLRenderingContext.INVALID_VALUE = 1281;
WebGLRenderingContext.prototype.INVALID_OPERATION = WebGLRenderingContext.INVALID_OPERATION = 1282;
WebGLRenderingContext.prototype.OUT_OF_MEMORY = WebGLRenderingContext.OUT_OF_MEMORY = 1285;
WebGLRenderingContext.prototype.CW = WebGLRenderingContext.CW = 2304;
WebGLRenderingContext.prototype.CCW = WebGLRenderingContext.CCW = 2305;
WebGLRenderingContext.prototype.LINE_WIDTH = WebGLRenderingContext.LINE_WIDTH = 2849;
WebGLRenderingContext.prototype.ALIASED_POINT_SIZE_RANGE = WebGLRenderingContext.ALIASED_POINT_SIZE_RANGE = 33901;
WebGLRenderingContext.prototype.ALIASED_LINE_WIDTH_RANGE = WebGLRenderingContext.ALIASED_LINE_WIDTH_RANGE = 33902;
WebGLRenderingContext.prototype.CULL_FACE_MODE = WebGLRenderingContext.CULL_FACE_MODE = 2885;
WebGLRenderingContext.prototype.FRONT_FACE = WebGLRenderingContext.FRONT_FACE = 2886;
WebGLRenderingContext.prototype.DEPTH_RANGE = WebGLRenderingContext.DEPTH_RANGE = 2928;
WebGLRenderingContext.prototype.DEPTH_WRITEMASK = WebGLRenderingContext.DEPTH_WRITEMASK = 2930;
WebGLRenderingContext.prototype.DEPTH_CLEAR_VALUE = WebGLRenderingContext.DEPTH_CLEAR_VALUE = 2931;
WebGLRenderingContext.prototype.DEPTH_FUNC = WebGLRenderingContext.DEPTH_FUNC = 2932;
WebGLRenderingContext.prototype.STENCIL_CLEAR_VALUE = WebGLRenderingContext.STENCIL_CLEAR_VALUE = 2961;
WebGLRenderingContext.prototype.STENCIL_FUNC = WebGLRenderingContext.STENCIL_FUNC = 2962;
WebGLRenderingContext.prototype.STENCIL_FAIL = WebGLRenderingContext.STENCIL_FAIL = 2964;
WebGLRenderingContext.prototype.STENCIL_PASS_DEPTH_FAIL = WebGLRenderingContext.STENCIL_PASS_DEPTH_FAIL = 2965;
WebGLRenderingContext.prototype.STENCIL_PASS_DEPTH_PASS = WebGLRenderingContext.STENCIL_PASS_DEPTH_PASS = 2966;
WebGLRenderingContext.prototype.STENCIL_REF = WebGLRenderingContext.STENCIL_REF = 2967;
WebGLRenderingContext.prototype.STENCIL_VALUE_MASK = WebGLRenderingContext.STENCIL_VALUE_MASK = 2963;
WebGLRenderingContext.prototype.STENCIL_WRITEMASK = WebGLRenderingContext.STENCIL_WRITEMASK = 2968;
WebGLRenderingContext.prototype.STENCIL_BACK_FUNC = WebGLRenderingContext.STENCIL_BACK_FUNC = 34816;
WebGLRenderingContext.prototype.STENCIL_BACK_FAIL = WebGLRenderingContext.STENCIL_BACK_FAIL = 34817;
WebGLRenderingContext.prototype.STENCIL_BACK_PASS_DEPTH_FAIL = WebGLRenderingContext.STENCIL_BACK_PASS_DEPTH_FAIL = 34818;
WebGLRenderingContext.prototype.STENCIL_BACK_PASS_DEPTH_PASS = WebGLRenderingContext.STENCIL_BACK_PASS_DEPTH_PASS = 34819;
WebGLRenderingContext.prototype.STENCIL_BACK_REF = WebGLRenderingContext.STENCIL_BACK_REF = 36003;
WebGLRenderingContext.prototype.STENCIL_BACK_VALUE_MASK = WebGLRenderingContext.STENCIL_BACK_VALUE_MASK = 36004;
WebGLRenderingContext.prototype.STENCIL_BACK_WRITEMASK = WebGLRenderingContext.STENCIL_BACK_WRITEMASK = 36005;
WebGLRenderingContext.prototype.VIEWPORT = WebGLRenderingContext.VIEWPORT = 2978;
WebGLRenderingContext.prototype.SCISSOR_BOX = WebGLRenderingContext.SCISSOR_BOX = 3088;
WebGLRenderingContext.prototype.COLOR_CLEAR_VALUE = WebGLRenderingContext.COLOR_CLEAR_VALUE = 3106;
WebGLRenderingContext.prototype.COLOR_WRITEMASK = WebGLRenderingContext.COLOR_WRITEMASK = 3107;
WebGLRenderingContext.prototype.UNPACK_ALIGNMENT = WebGLRenderingContext.UNPACK_ALIGNMENT = 3317;
WebGLRenderingContext.prototype.PACK_ALIGNMENT = WebGLRenderingContext.PACK_ALIGNMENT = 3333;
WebGLRenderingContext.prototype.MAX_TEXTURE_SIZE = WebGLRenderingContext.MAX_TEXTURE_SIZE = 3379;
WebGLRenderingContext.prototype.MAX_VIEWPORT_DIMS = WebGLRenderingContext.MAX_VIEWPORT_DIMS = 3386;
WebGLRenderingContext.prototype.SUBPIXEL_BITS = WebGLRenderingContext.SUBPIXEL_BITS = 3408;
WebGLRenderingContext.prototype.RED_BITS = WebGLRenderingContext.RED_BITS = 3410;
WebGLRenderingContext.prototype.GREEN_BITS = WebGLRenderingContext.GREEN_BITS = 3411;
WebGLRenderingContext.prototype.BLUE_BITS = WebGLRenderingContext.BLUE_BITS = 3412;
WebGLRenderingContext.prototype.ALPHA_BITS = WebGLRenderingContext.ALPHA_BITS = 3413;
WebGLRenderingContext.prototype.DEPTH_BITS = WebGLRenderingContext.DEPTH_BITS = 3414;
WebGLRenderingContext.prototype.STENCIL_BITS = WebGLRenderingContext.STENCIL_BITS = 3415;
WebGLRenderingContext.prototype.POLYGON_OFFSET_UNITS = WebGLRenderingContext.POLYGON_OFFSET_UNITS = 10752;
WebGLRenderingContext.prototype.POLYGON_OFFSET_FACTOR = WebGLRenderingContext.POLYGON_OFFSET_FACTOR = 32824;
WebGLRenderingContext.prototype.TEXTURE_BINDING_2D = WebGLRenderingContext.TEXTURE_BINDING_2D = 32873;
WebGLRenderingContext.prototype.SAMPLE_BUFFERS = WebGLRenderingContext.SAMPLE_BUFFERS = 32936;
WebGLRenderingContext.prototype.SAMPLES = WebGLRenderingContext.SAMPLES = 32937;
WebGLRenderingContext.prototype.SAMPLE_COVERAGE_VALUE = WebGLRenderingContext.SAMPLE_COVERAGE_VALUE = 32938;
WebGLRenderingContext.prototype.SAMPLE_COVERAGE_INVERT = WebGLRenderingContext.SAMPLE_COVERAGE_INVERT = 32939;
WebGLRenderingContext.prototype.COMPRESSED_TEXTURE_FORMATS = WebGLRenderingContext.COMPRESSED_TEXTURE_FORMATS = 34467;
WebGLRenderingContext.prototype.DONT_CARE = WebGLRenderingContext.DONT_CARE = 4352;
WebGLRenderingContext.prototype.FASTEST = WebGLRenderingContext.FASTEST = 4353;
WebGLRenderingContext.prototype.NICEST = WebGLRenderingContext.NICEST = 4354;
WebGLRenderingContext.prototype.GENERATE_MIPMAP_HINT = WebGLRenderingContext.GENERATE_MIPMAP_HINT = 33170;
WebGLRenderingContext.prototype.BYTE = WebGLRenderingContext.BYTE = 5120;
WebGLRenderingContext.prototype.UNSIGNED_BYTE = WebGLRenderingContext.UNSIGNED_BYTE = 5121;
WebGLRenderingContext.prototype.SHORT = WebGLRenderingContext.SHORT = 5122;
WebGLRenderingContext.prototype.UNSIGNED_SHORT = WebGLRenderingContext.UNSIGNED_SHORT = 5123;
WebGLRenderingContext.prototype.INT = WebGLRenderingContext.INT = 5124;
WebGLRenderingContext.prototype.UNSIGNED_INT = WebGLRenderingContext.UNSIGNED_INT = 5125;
WebGLRenderingContext.prototype.FLOAT = WebGLRenderingContext.FLOAT = 5126;
WebGLRenderingContext.prototype.DEPTH_COMPONENT = WebGLRenderingContext.DEPTH_COMPONENT = 6402;
WebGLRenderingContext.prototype.ALPHA = WebGLRenderingContext.ALPHA = 6406;
WebGLRenderingContext.prototype.RGB = WebGLRenderingContext.RGB = 6407;
WebGLRenderingContext.prototype.RGBA = WebGLRenderingContext.RGBA = 6408;
WebGLRenderingContext.prototype.LUMINANCE = WebGLRenderingContext.LUMINANCE = 6409;
WebGLRenderingContext.prototype.LUMINANCE_ALPHA = WebGLRenderingContext.LUMINANCE_ALPHA = 6410;
WebGLRenderingContext.prototype.UNSIGNED_SHORT_4_4_4_4 = WebGLRenderingContext.UNSIGNED_SHORT_4_4_4_4 = 32819;
WebGLRenderingContext.prototype.UNSIGNED_SHORT_5_5_5_1 = WebGLRenderingContext.UNSIGNED_SHORT_5_5_5_1 = 32820;
WebGLRenderingContext.prototype.UNSIGNED_SHORT_5_6_5 = WebGLRenderingContext.UNSIGNED_SHORT_5_6_5 = 33635;
WebGLRenderingContext.prototype.FRAGMENT_SHADER = WebGLRenderingContext.FRAGMENT_SHADER = 35632;
WebGLRenderingContext.prototype.VERTEX_SHADER = WebGLRenderingContext.VERTEX_SHADER = 35633;
WebGLRenderingContext.prototype.MAX_VERTEX_ATTRIBS = WebGLRenderingContext.MAX_VERTEX_ATTRIBS = 34921;
WebGLRenderingContext.prototype.MAX_VERTEX_UNIFORM_VECTORS = WebGLRenderingContext.MAX_VERTEX_UNIFORM_VECTORS = 36347;
WebGLRenderingContext.prototype.MAX_VARYING_VECTORS = WebGLRenderingContext.MAX_VARYING_VECTORS = 36348;
WebGLRenderingContext.prototype.MAX_COMBINED_TEXTURE_IMAGE_UNITS = WebGLRenderingContext.MAX_COMBINED_TEXTURE_IMAGE_UNITS = 35661;
WebGLRenderingContext.prototype.MAX_VERTEX_TEXTURE_IMAGE_UNITS = WebGLRenderingContext.MAX_VERTEX_TEXTURE_IMAGE_UNITS = 35660;
WebGLRenderingContext.prototype.MAX_TEXTURE_IMAGE_UNITS = WebGLRenderingContext.MAX_TEXTURE_IMAGE_UNITS = 34930;
WebGLRenderingContext.prototype.MAX_FRAGMENT_UNIFORM_VECTORS = WebGLRenderingContext.MAX_FRAGMENT_UNIFORM_VECTORS = 36349;
WebGLRenderingContext.prototype.SHADER_TYPE = WebGLRenderingContext.SHADER_TYPE = 35663;
WebGLRenderingContext.prototype.DELETE_STATUS = WebGLRenderingContext.DELETE_STATUS = 35712;
WebGLRenderingContext.prototype.LINK_STATUS = WebGLRenderingContext.LINK_STATUS = 35714;
WebGLRenderingContext.prototype.VALIDATE_STATUS = WebGLRenderingContext.VALIDATE_STATUS = 35715;
WebGLRenderingContext.prototype.ATTACHED_SHADERS = WebGLRenderingContext.ATTACHED_SHADERS = 35717;
WebGLRenderingContext.prototype.ACTIVE_UNIFORMS = WebGLRenderingContext.ACTIVE_UNIFORMS = 35718;
WebGLRenderingContext.prototype.ACTIVE_ATTRIBUTES = WebGLRenderingContext.ACTIVE_ATTRIBUTES = 35721;
WebGLRenderingContext.prototype.SHADING_LANGUAGE_VERSION = WebGLRenderingContext.SHADING_LANGUAGE_VERSION = 35724;
WebGLRenderingContext.prototype.CURRENT_PROGRAM = WebGLRenderingContext.CURRENT_PROGRAM = 35725;
WebGLRenderingContext.prototype.NEVER = WebGLRenderingContext.NEVER = 512;
WebGLRenderingContext.prototype.LESS = WebGLRenderingContext.LESS = 513;
WebGLRenderingContext.prototype.EQUAL = WebGLRenderingContext.EQUAL = 514;
WebGLRenderingContext.prototype.LEQUAL = WebGLRenderingContext.LEQUAL = 515;
WebGLRenderingContext.prototype.GREATER = WebGLRenderingContext.GREATER = 516;
WebGLRenderingContext.prototype.NOTEQUAL = WebGLRenderingContext.NOTEQUAL = 517;
WebGLRenderingContext.prototype.GEQUAL = WebGLRenderingContext.GEQUAL = 518;
WebGLRenderingContext.prototype.ALWAYS = WebGLRenderingContext.ALWAYS = 519;
WebGLRenderingContext.prototype.KEEP = WebGLRenderingContext.KEEP = 7680;
WebGLRenderingContext.prototype.REPLACE = WebGLRenderingContext.REPLACE = 7681;
WebGLRenderingContext.prototype.INCR = WebGLRenderingContext.INCR = 7682;
WebGLRenderingContext.prototype.DECR = WebGLRenderingContext.DECR = 7683;
WebGLRenderingContext.prototype.INVERT = WebGLRenderingContext.INVERT = 5386;
WebGLRenderingContext.prototype.INCR_WRAP = WebGLRenderingContext.INCR_WRAP = 34055;
WebGLRenderingContext.prototype.DECR_WRAP = WebGLRenderingContext.DECR_WRAP = 34056;
WebGLRenderingContext.prototype.VENDOR = WebGLRenderingContext.VENDOR = 7936;
WebGLRenderingContext.prototype.RENDERER = WebGLRenderingContext.RENDERER = 7937;
WebGLRenderingContext.prototype.VERSION = WebGLRenderingContext.VERSION = 7938;
WebGLRenderingContext.prototype.NEAREST = WebGLRenderingContext.NEAREST = 9728;
WebGLRenderingContext.prototype.LINEAR = WebGLRenderingContext.LINEAR = 9729;
WebGLRenderingContext.prototype.NEAREST_MIPMAP_NEAREST = WebGLRenderingContext.NEAREST_MIPMAP_NEAREST = 9984;
WebGLRenderingContext.prototype.LINEAR_MIPMAP_NEAREST = WebGLRenderingContext.LINEAR_MIPMAP_NEAREST = 9985;
WebGLRenderingContext.prototype.NEAREST_MIPMAP_LINEAR = WebGLRenderingContext.NEAREST_MIPMAP_LINEAR = 9986;
WebGLRenderingContext.prototype.LINEAR_MIPMAP_LINEAR = WebGLRenderingContext.LINEAR_MIPMAP_LINEAR = 9987;
WebGLRenderingContext.prototype.TEXTURE_MAG_FILTER = WebGLRenderingContext.TEXTURE_MAG_FILTER = 10240;
WebGLRenderingContext.prototype.TEXTURE_MIN_FILTER = WebGLRenderingContext.TEXTURE_MIN_FILTER = 10241;
WebGLRenderingContext.prototype.TEXTURE_WRAP_S = WebGLRenderingContext.TEXTURE_WRAP_S = 10242;
WebGLRenderingContext.prototype.TEXTURE_WRAP_T = WebGLRenderingContext.TEXTURE_WRAP_T = 10243;
WebGLRenderingContext.prototype.TEXTURE = WebGLRenderingContext.TEXTURE = 5890;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP = WebGLRenderingContext.TEXTURE_CUBE_MAP = 34067;
WebGLRenderingContext.prototype.TEXTURE_BINDING_CUBE_MAP = WebGLRenderingContext.TEXTURE_BINDING_CUBE_MAP = 34068;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_POSITIVE_X = WebGLRenderingContext.TEXTURE_CUBE_MAP_POSITIVE_X = 34069;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_NEGATIVE_X = WebGLRenderingContext.TEXTURE_CUBE_MAP_NEGATIVE_X = 34070;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_POSITIVE_Y = WebGLRenderingContext.TEXTURE_CUBE_MAP_POSITIVE_Y = 34071;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_NEGATIVE_Y = WebGLRenderingContext.TEXTURE_CUBE_MAP_NEGATIVE_Y = 34072;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_POSITIVE_Z = WebGLRenderingContext.TEXTURE_CUBE_MAP_POSITIVE_Z = 34073;
WebGLRenderingContext.prototype.TEXTURE_CUBE_MAP_NEGATIVE_Z = WebGLRenderingContext.TEXTURE_CUBE_MAP_NEGATIVE_Z = 34074;
WebGLRenderingContext.prototype.MAX_CUBE_MAP_TEXTURE_SIZE = WebGLRenderingContext.MAX_CUBE_MAP_TEXTURE_SIZE = 34076;
WebGLRenderingContext.prototype.TEXTURE0 = WebGLRenderingContext.TEXTURE0 = 33984;
WebGLRenderingContext.prototype.TEXTURE1 = WebGLRenderingContext.TEXTURE1 = 33985;
WebGLRenderingContext.prototype.TEXTURE2 = WebGLRenderingContext.TEXTURE2 = 33986;
WebGLRenderingContext.prototype.TEXTURE3 = WebGLRenderingContext.TEXTURE3 = 33987;
WebGLRenderingContext.prototype.TEXTURE4 = WebGLRenderingContext.TEXTURE4 = 33988;
WebGLRenderingContext.prototype.TEXTURE5 = WebGLRenderingContext.TEXTURE5 = 33989;
WebGLRenderingContext.prototype.TEXTURE6 = WebGLRenderingContext.TEXTURE6 = 33990;
WebGLRenderingContext.prototype.TEXTURE7 = WebGLRenderingContext.TEXTURE7 = 33991;
WebGLRenderingContext.prototype.TEXTURE8 = WebGLRenderingContext.TEXTURE8 = 33992;
WebGLRenderingContext.prototype.TEXTURE9 = WebGLRenderingContext.TEXTURE9 = 33993;
WebGLRenderingContext.prototype.TEXTURE10 = WebGLRenderingContext.TEXTURE10 = 33994;
WebGLRenderingContext.prototype.TEXTURE11 = WebGLRenderingContext.TEXTURE11 = 33995;
WebGLRenderingContext.prototype.TEXTURE12 = WebGLRenderingContext.TEXTURE12 = 33996;
WebGLRenderingContext.prototype.TEXTURE13 = WebGLRenderingContext.TEXTURE13 = 33997;
WebGLRenderingContext.prototype.TEXTURE14 = WebGLRenderingContext.TEXTURE14 = 33998;
WebGLRenderingContext.prototype.TEXTURE15 = WebGLRenderingContext.TEXTURE15 = 33999;
WebGLRenderingContext.prototype.TEXTURE16 = WebGLRenderingContext.TEXTURE16 = 34000;
WebGLRenderingContext.prototype.TEXTURE17 = WebGLRenderingContext.TEXTURE17 = 34001;
WebGLRenderingContext.prototype.TEXTURE18 = WebGLRenderingContext.TEXTURE18 = 34002;
WebGLRenderingContext.prototype.TEXTURE19 = WebGLRenderingContext.TEXTURE19 = 34003;
WebGLRenderingContext.prototype.TEXTURE20 = WebGLRenderingContext.TEXTURE20 = 34004;
WebGLRenderingContext.prototype.TEXTURE21 = WebGLRenderingContext.TEXTURE21 = 34005;
WebGLRenderingContext.prototype.TEXTURE22 = WebGLRenderingContext.TEXTURE22 = 34006;
WebGLRenderingContext.prototype.TEXTURE23 = WebGLRenderingContext.TEXTURE23 = 34007;
WebGLRenderingContext.prototype.TEXTURE24 = WebGLRenderingContext.TEXTURE24 = 34008;
WebGLRenderingContext.prototype.TEXTURE25 = WebGLRenderingContext.TEXTURE25 = 34009;
WebGLRenderingContext.prototype.TEXTURE26 = WebGLRenderingContext.TEXTURE26 = 34010;
WebGLRenderingContext.prototype.TEXTURE27 = WebGLRenderingContext.TEXTURE27 = 34011;
WebGLRenderingContext.prototype.TEXTURE28 = WebGLRenderingContext.TEXTURE28 = 34012;
WebGLRenderingContext.prototype.TEXTURE29 = WebGLRenderingContext.TEXTURE29 = 34013;
WebGLRenderingContext.prototype.TEXTURE30 = WebGLRenderingContext.TEXTURE30 = 34014;
WebGLRenderingContext.prototype.TEXTURE31 = WebGLRenderingContext.TEXTURE31 = 34015;
WebGLRenderingContext.prototype.ACTIVE_TEXTURE = WebGLRenderingContext.ACTIVE_TEXTURE = 34016;
WebGLRenderingContext.prototype.REPEAT = WebGLRenderingContext.REPEAT = 10497;
WebGLRenderingContext.prototype.CLAMP_TO_EDGE = WebGLRenderingContext.CLAMP_TO_EDGE = 33071;
WebGLRenderingContext.prototype.MIRRORED_REPEAT = WebGLRenderingContext.MIRRORED_REPEAT = 33648;
WebGLRenderingContext.prototype.FLOAT_VEC2 = WebGLRenderingContext.FLOAT_VEC2 = 35664;
WebGLRenderingContext.prototype.FLOAT_VEC3 = WebGLRenderingContext.FLOAT_VEC3 = 35665;
WebGLRenderingContext.prototype.FLOAT_VEC4 = WebGLRenderingContext.FLOAT_VEC4 = 35666;
WebGLRenderingContext.prototype.INT_VEC2 = WebGLRenderingContext.INT_VEC2 = 35667;
WebGLRenderingContext.prototype.INT_VEC3 = WebGLRenderingContext.INT_VEC3 = 35668;
WebGLRenderingContext.prototype.INT_VEC4 = WebGLRenderingContext.INT_VEC4 = 35669;
WebGLRenderingContext.prototype.BOOL = WebGLRenderingContext.BOOL = 35670;
WebGLRenderingContext.prototype.BOOL_VEC2 = WebGLRenderingContext.BOOL_VEC2 = 35671;
WebGLRenderingContext.prototype.BOOL_VEC3 = WebGLRenderingContext.BOOL_VEC3 = 35672;
WebGLRenderingContext.prototype.BOOL_VEC4 = WebGLRenderingContext.BOOL_VEC4 = 35673;
WebGLRenderingContext.prototype.FLOAT_MAT2 = WebGLRenderingContext.FLOAT_MAT2 = 35674;
WebGLRenderingContext.prototype.FLOAT_MAT3 = WebGLRenderingContext.FLOAT_MAT3 = 35675;
WebGLRenderingContext.prototype.FLOAT_MAT4 = WebGLRenderingContext.FLOAT_MAT4 = 35676;
WebGLRenderingContext.prototype.SAMPLER_2D = WebGLRenderingContext.SAMPLER_2D = 35678;
WebGLRenderingContext.prototype.SAMPLER_CUBE = WebGLRenderingContext.SAMPLER_CUBE = 35680;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_ENABLED = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_ENABLED = 34338;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_SIZE = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_SIZE = 34339;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_STRIDE = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_STRIDE = 34340;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_TYPE = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_TYPE = 34341;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_NORMALIZED = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_NORMALIZED = 34922;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_POINTER = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_POINTER = 34373;
WebGLRenderingContext.prototype.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = WebGLRenderingContext.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 34975;
WebGLRenderingContext.prototype.IMPLEMENTATION_COLOR_READ_TYPE = WebGLRenderingContext.IMPLEMENTATION_COLOR_READ_TYPE = 35738;
WebGLRenderingContext.prototype.IMPLEMENTATION_COLOR_READ_FORMAT = WebGLRenderingContext.IMPLEMENTATION_COLOR_READ_FORMAT = 35739;
WebGLRenderingContext.prototype.COMPILE_STATUS = WebGLRenderingContext.COMPILE_STATUS = 35713;
WebGLRenderingContext.prototype.LOW_FLOAT = WebGLRenderingContext.LOW_FLOAT = 36336;
WebGLRenderingContext.prototype.MEDIUM_FLOAT = WebGLRenderingContext.MEDIUM_FLOAT = 36337;
WebGLRenderingContext.prototype.HIGH_FLOAT = WebGLRenderingContext.HIGH_FLOAT = 36338;
WebGLRenderingContext.prototype.LOW_INT = WebGLRenderingContext.LOW_INT = 36339;
WebGLRenderingContext.prototype.MEDIUM_INT = WebGLRenderingContext.MEDIUM_INT = 36340;
WebGLRenderingContext.prototype.HIGH_INT = WebGLRenderingContext.HIGH_INT = 36341;
WebGLRenderingContext.prototype.FRAMEBUFFER = WebGLRenderingContext.FRAMEBUFFER = 36160;
WebGLRenderingContext.prototype.RENDERBUFFER = WebGLRenderingContext.RENDERBUFFER = 36161;
WebGLRenderingContext.prototype.RGBA4 = WebGLRenderingContext.RGBA4 = 32854;
WebGLRenderingContext.prototype.RGB5_A1 = WebGLRenderingContext.RGB5_A1 = 32855;
WebGLRenderingContext.prototype.RGB565 = WebGLRenderingContext.RGB565 = 36194;
WebGLRenderingContext.prototype.DEPTH_COMPONENT16 = WebGLRenderingContext.DEPTH_COMPONENT16 = 33189;
WebGLRenderingContext.prototype.STENCIL_INDEX8 = WebGLRenderingContext.STENCIL_INDEX8 = 36168;
WebGLRenderingContext.prototype.DEPTH_STENCIL = WebGLRenderingContext.DEPTH_STENCIL = 34041;
WebGLRenderingContext.prototype.RENDERBUFFER_WIDTH = WebGLRenderingContext.RENDERBUFFER_WIDTH = 36162;
WebGLRenderingContext.prototype.RENDERBUFFER_HEIGHT = WebGLRenderingContext.RENDERBUFFER_HEIGHT = 36163;
WebGLRenderingContext.prototype.RENDERBUFFER_INTERNAL_FORMAT = WebGLRenderingContext.RENDERBUFFER_INTERNAL_FORMAT = 36164;
WebGLRenderingContext.prototype.RENDERBUFFER_RED_SIZE = WebGLRenderingContext.RENDERBUFFER_RED_SIZE = 36176;
WebGLRenderingContext.prototype.RENDERBUFFER_GREEN_SIZE = WebGLRenderingContext.RENDERBUFFER_GREEN_SIZE = 36177;
WebGLRenderingContext.prototype.RENDERBUFFER_BLUE_SIZE = WebGLRenderingContext.RENDERBUFFER_BLUE_SIZE = 36178;
WebGLRenderingContext.prototype.RENDERBUFFER_ALPHA_SIZE = WebGLRenderingContext.RENDERBUFFER_ALPHA_SIZE = 36179;
WebGLRenderingContext.prototype.RENDERBUFFER_DEPTH_SIZE = WebGLRenderingContext.RENDERBUFFER_DEPTH_SIZE = 36180;
WebGLRenderingContext.prototype.RENDERBUFFER_STENCIL_SIZE = WebGLRenderingContext.RENDERBUFFER_STENCIL_SIZE = 36181;
WebGLRenderingContext.prototype.FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = WebGLRenderingContext.FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 36048;
WebGLRenderingContext.prototype.FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = WebGLRenderingContext.FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 36049;
WebGLRenderingContext.prototype.FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = WebGLRenderingContext.FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 36050;
WebGLRenderingContext.prototype.FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = WebGLRenderingContext.FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 36051;
WebGLRenderingContext.prototype.COLOR_ATTACHMENT0 = WebGLRenderingContext.COLOR_ATTACHMENT0 = 36064;
WebGLRenderingContext.prototype.DEPTH_ATTACHMENT = WebGLRenderingContext.DEPTH_ATTACHMENT = 36096;
WebGLRenderingContext.prototype.STENCIL_ATTACHMENT = WebGLRenderingContext.STENCIL_ATTACHMENT = 36128;
WebGLRenderingContext.prototype.DEPTH_STENCIL_ATTACHMENT = WebGLRenderingContext.DEPTH_STENCIL_ATTACHMENT = 33306;
WebGLRenderingContext.prototype.NONE = WebGLRenderingContext.NONE = 0;
WebGLRenderingContext.prototype.FRAMEBUFFER_COMPLETE = WebGLRenderingContext.FRAMEBUFFER_COMPLETE = 36053;
WebGLRenderingContext.prototype.FRAMEBUFFER_INCOMPLETE_ATTACHMENT = WebGLRenderingContext.FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 36054;
WebGLRenderingContext.prototype.FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = WebGLRenderingContext.FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 36055;
WebGLRenderingContext.prototype.FRAMEBUFFER_INCOMPLETE_DIMENSIONS = WebGLRenderingContext.FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 36057;
WebGLRenderingContext.prototype.FRAMEBUFFER_UNSUPPORTED = WebGLRenderingContext.FRAMEBUFFER_UNSUPPORTED = 36061;
WebGLRenderingContext.prototype.FRAMEBUFFER_BINDING = WebGLRenderingContext.FRAMEBUFFER_BINDING = 36006;
WebGLRenderingContext.prototype.RENDERBUFFER_BINDING = WebGLRenderingContext.RENDERBUFFER_BINDING = 36007;
WebGLRenderingContext.prototype.MAX_RENDERBUFFER_SIZE = WebGLRenderingContext.MAX_RENDERBUFFER_SIZE = 34024;
WebGLRenderingContext.prototype.INVALID_FRAMEBUFFER_OPERATION = WebGLRenderingContext.INVALID_FRAMEBUFFER_OPERATION = 1286;
WebGLRenderingContext.prototype.UNPACK_FLIP_Y_WEBGL = WebGLRenderingContext.UNPACK_FLIP_Y_WEBGL = 37440;
WebGLRenderingContext.prototype.UNPACK_PREMULTIPLY_ALPHA_WEBGL = WebGLRenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL = 37441;
WebGLRenderingContext.prototype.CONTEXT_LOST_WEBGL = WebGLRenderingContext.CONTEXT_LOST_WEBGL = 37442;
WebGLRenderingContext.prototype.UNPACK_COLORSPACE_CONVERSION_WEBGL = WebGLRenderingContext.UNPACK_COLORSPACE_CONVERSION_WEBGL = 37443;
WebGLRenderingContext.prototype.BROWSER_DEFAULT_WEBGL = WebGLRenderingContext.BROWSER_DEFAULT_WEBGL = 37444;

WebGLRenderingContext.prototype["activeTexture"] = rsvm.browser.WebGLRenderingContext.actor.activeTexture;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.activeTexture, "length", { value: 1 });
WebGLRenderingContext.prototype["attachShader"] = rsvm.browser.WebGLRenderingContext.actor.attachShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.attachShader, "length", { value: 2 });
WebGLRenderingContext.prototype["bindAttribLocation"] = rsvm.browser.WebGLRenderingContext.actor.bindAttribLocation;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bindAttribLocation, "length", { value: 3 });
WebGLRenderingContext.prototype["bindRenderbuffer"] = rsvm.browser.WebGLRenderingContext.actor.bindRenderbuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bindRenderbuffer, "length", { value: 2 });
WebGLRenderingContext.prototype["blendColor"] = rsvm.browser.WebGLRenderingContext.actor.blendColor;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.blendColor, "length", { value: 4 });
WebGLRenderingContext.prototype["blendEquation"] = rsvm.browser.WebGLRenderingContext.actor.blendEquation;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.blendEquation, "length", { value: 1 });
WebGLRenderingContext.prototype["blendEquationSeparate"] = rsvm.browser.WebGLRenderingContext.actor.blendEquationSeparate;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.blendEquationSeparate, "length", { value: 2 });
WebGLRenderingContext.prototype["blendFunc"] = rsvm.browser.WebGLRenderingContext.actor.blendFunc;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.blendFunc, "length", { value: 2 });
WebGLRenderingContext.prototype["blendFuncSeparate"] = rsvm.browser.WebGLRenderingContext.actor.blendFuncSeparate;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.blendFuncSeparate, "length", { value: 4 });
WebGLRenderingContext.prototype["bufferData"] = rsvm.browser.WebGLRenderingContext.actor.bufferData;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bufferData, "length", { value: 3 });
WebGLRenderingContext.prototype["bufferSubData"] = rsvm.browser.WebGLRenderingContext.actor.bufferSubData;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bufferSubData, "length", { value: 3 });
WebGLRenderingContext.prototype["checkFramebufferStatus"] = rsvm.browser.WebGLRenderingContext.actor.checkFramebufferStatus;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.checkFramebufferStatus, "length", { value: 1 });
WebGLRenderingContext.prototype["compileShader"] = rsvm.browser.WebGLRenderingContext.actor.compileShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.compileShader, "length", { value: 1 });
WebGLRenderingContext.prototype["compressedTexImage2D"] = rsvm.browser.WebGLRenderingContext.actor.compressedTexImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.compressedTexImage2D, "length", { value: 7 });
WebGLRenderingContext.prototype["compressedTexSubImage2D"] = rsvm.browser.WebGLRenderingContext.actor.compressedTexSubImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.compressedTexSubImage2D, "length", { value: 8 });
WebGLRenderingContext.prototype["copyTexImage2D"] = rsvm.browser.WebGLRenderingContext.actor.copyTexImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.copyTexImage2D, "length", { value: 8 });
WebGLRenderingContext.prototype["copyTexSubImage2D"] = rsvm.browser.WebGLRenderingContext.actor.copyTexSubImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.copyTexSubImage2D, "length", { value: 8 });
WebGLRenderingContext.prototype["createBuffer"] = rsvm.browser.WebGLRenderingContext.actor.createBuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createBuffer, "length", { value: 0 });
WebGLRenderingContext.prototype["createFramebuffer"] = rsvm.browser.WebGLRenderingContext.actor.createFramebuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createFramebuffer, "length", { value: 0 });
WebGLRenderingContext.prototype["createProgram"] = rsvm.browser.WebGLRenderingContext.actor.createProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createProgram, "length", { value: 0 });
WebGLRenderingContext.prototype["createRenderbuffer"] = rsvm.browser.WebGLRenderingContext.actor.createRenderbuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createRenderbuffer, "length", { value: 0 });
WebGLRenderingContext.prototype["createShader"] = rsvm.browser.WebGLRenderingContext.actor.createShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createShader, "length", { value: 1 });
WebGLRenderingContext.prototype["createTexture"] = rsvm.browser.WebGLRenderingContext.actor.createTexture;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.createTexture, "length", { value: 0 });
WebGLRenderingContext.prototype["cullFace"] = rsvm.browser.WebGLRenderingContext.actor.cullFace;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.cullFace, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteBuffer"] = rsvm.browser.WebGLRenderingContext.actor.deleteBuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteBuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteFramebuffer"] = rsvm.browser.WebGLRenderingContext.actor.deleteFramebuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteFramebuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteProgram"] = rsvm.browser.WebGLRenderingContext.actor.deleteProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteProgram, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteRenderbuffer"] = rsvm.browser.WebGLRenderingContext.actor.deleteRenderbuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteRenderbuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteShader"] = rsvm.browser.WebGLRenderingContext.actor.deleteShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteShader, "length", { value: 1 });
WebGLRenderingContext.prototype["deleteTexture"] = rsvm.browser.WebGLRenderingContext.actor.deleteTexture;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.deleteTexture, "length", { value: 1 });
WebGLRenderingContext.prototype["depthFunc"] = rsvm.browser.WebGLRenderingContext.actor.depthFunc;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.depthFunc, "length", { value: 1 });
WebGLRenderingContext.prototype["depthMask"] = rsvm.browser.WebGLRenderingContext.actor.depthMask;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.depthMask, "length", { value: 1 });
WebGLRenderingContext.prototype["depthRange"] = rsvm.browser.WebGLRenderingContext.actor.depthRange;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.depthRange, "length", { value: 2 });
WebGLRenderingContext.prototype["detachShader"] = rsvm.browser.WebGLRenderingContext.actor.detachShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.detachShader, "length", { value: 2 });
WebGLRenderingContext.prototype["disable"] = rsvm.browser.WebGLRenderingContext.actor.disable;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.disable, "length", { value: 1 });
WebGLRenderingContext.prototype["enable"] = rsvm.browser.WebGLRenderingContext.actor.enable;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.enable, "length", { value: 1 });
WebGLRenderingContext.prototype["finish"] = rsvm.browser.WebGLRenderingContext.actor.finish;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.finish, "length", { value: 0 });
WebGLRenderingContext.prototype["flush"] = rsvm.browser.WebGLRenderingContext.actor.flush;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.flush, "length", { value: 0 });
WebGLRenderingContext.prototype["framebufferRenderbuffer"] = rsvm.browser.WebGLRenderingContext.actor.framebufferRenderbuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.framebufferRenderbuffer, "length", { value: 4 });
WebGLRenderingContext.prototype["framebufferTexture2D"] = rsvm.browser.WebGLRenderingContext.actor.framebufferTexture2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.framebufferTexture2D, "length", { value: 5 });
WebGLRenderingContext.prototype["frontFace"] = rsvm.browser.WebGLRenderingContext.actor.frontFace;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.frontFace, "length", { value: 1 });
WebGLRenderingContext.prototype["generateMipmap"] = rsvm.browser.WebGLRenderingContext.actor.generateMipmap;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.generateMipmap, "length", { value: 1 });
WebGLRenderingContext.prototype["getActiveAttrib"] = rsvm.browser.WebGLRenderingContext.actor.getActiveAttrib;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getActiveAttrib, "length", { value: 2 });
WebGLRenderingContext.prototype["getActiveUniform"] = rsvm.browser.WebGLRenderingContext.actor.getActiveUniform;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getActiveUniform, "length", { value: 2 });
WebGLRenderingContext.prototype["getAttachedShaders"] = rsvm.browser.WebGLRenderingContext.actor.getAttachedShaders;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getAttachedShaders, "length", { value: 1 });
WebGLRenderingContext.prototype["getAttribLocation"] = rsvm.browser.WebGLRenderingContext.actor.getAttribLocation;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getAttribLocation, "length", { value: 2 });
WebGLRenderingContext.prototype["getBufferParameter"] = rsvm.browser.WebGLRenderingContext.actor.getBufferParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getBufferParameter, "length", { value: 2 });
WebGLRenderingContext.prototype["getContextAttributes"] = rsvm.browser.WebGLRenderingContext.actor.getContextAttributes;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getContextAttributes, "length", { value: 0 });
WebGLRenderingContext.prototype["getError"] = rsvm.browser.WebGLRenderingContext.actor.getError;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getError, "length", { value: 0 });
WebGLRenderingContext.prototype["getExtension"] = rsvm.browser.WebGLRenderingContext.actor.getExtension;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getExtension, "length", { value: 1 });
WebGLRenderingContext.prototype["getFramebufferAttachmentParameter"] = rsvm.browser.WebGLRenderingContext.actor.getFramebufferAttachmentParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getFramebufferAttachmentParameter, "length", { value: 3 });
WebGLRenderingContext.prototype["getParameter"] = rsvm.browser.WebGLRenderingContext.actor.getParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getParameter, "length", { value: 1 });
WebGLRenderingContext.prototype["getProgramInfoLog"] = rsvm.browser.WebGLRenderingContext.actor.getProgramInfoLog;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getProgramInfoLog, "length", { value: 1 });
WebGLRenderingContext.prototype["getProgramParameter"] = rsvm.browser.WebGLRenderingContext.actor.getProgramParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getProgramParameter, "length", { value: 2 });
WebGLRenderingContext.prototype["getRenderbufferParameter"] = rsvm.browser.WebGLRenderingContext.actor.getRenderbufferParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getRenderbufferParameter, "length", { value: 2 });
WebGLRenderingContext.prototype["getShaderInfoLog"] = rsvm.browser.WebGLRenderingContext.actor.getShaderInfoLog;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getShaderInfoLog, "length", { value: 1 });
WebGLRenderingContext.prototype["getShaderParameter"] = rsvm.browser.WebGLRenderingContext.actor.getShaderParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getShaderParameter, "length", { value: 2 });
WebGLRenderingContext.prototype["getShaderPrecisionFormat"] = rsvm.browser.WebGLRenderingContext.actor.getShaderPrecisionFormat;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getShaderPrecisionFormat, "length", { value: 2 });
WebGLRenderingContext.prototype["getShaderSource"] = rsvm.browser.WebGLRenderingContext.actor.getShaderSource;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getShaderSource, "length", { value: 1 });
WebGLRenderingContext.prototype["getSupportedExtensions"] = rsvm.browser.WebGLRenderingContext.actor.getSupportedExtensions;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getSupportedExtensions, "length", { value: 0 });
WebGLRenderingContext.prototype["getTexParameter"] = rsvm.browser.WebGLRenderingContext.actor.getTexParameter;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getTexParameter, "length", { value: 2 });
WebGLRenderingContext.prototype["getUniform"] = rsvm.browser.WebGLRenderingContext.actor.getUniform;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getUniform, "length", { value: 2 });
WebGLRenderingContext.prototype["getUniformLocation"] = rsvm.browser.WebGLRenderingContext.actor.getUniformLocation;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getUniformLocation, "length", { value: 2 });
WebGLRenderingContext.prototype["getVertexAttrib"] = rsvm.browser.WebGLRenderingContext.actor.getVertexAttrib;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getVertexAttrib, "length", { value: 2 });
WebGLRenderingContext.prototype["getVertexAttribOffset"] = rsvm.browser.WebGLRenderingContext.actor.getVertexAttribOffset;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.getVertexAttribOffset, "length", { value: 2 });
WebGLRenderingContext.prototype["hint"] = rsvm.browser.WebGLRenderingContext.actor.hint;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.hint, "length", { value: 2 });
WebGLRenderingContext.prototype["isBuffer"] = rsvm.browser.WebGLRenderingContext.actor.isBuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isBuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["isContextLost"] = rsvm.browser.WebGLRenderingContext.actor.isContextLost;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isContextLost, "length", { value: 0 });
WebGLRenderingContext.prototype["isEnabled"] = rsvm.browser.WebGLRenderingContext.actor.isEnabled;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isEnabled, "length", { value: 1 });
WebGLRenderingContext.prototype["isFramebuffer"] = rsvm.browser.WebGLRenderingContext.actor.isFramebuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isFramebuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["isProgram"] = rsvm.browser.WebGLRenderingContext.actor.isProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isProgram, "length", { value: 1 });
WebGLRenderingContext.prototype["isRenderbuffer"] = rsvm.browser.WebGLRenderingContext.actor.isRenderbuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isRenderbuffer, "length", { value: 1 });
WebGLRenderingContext.prototype["isShader"] = rsvm.browser.WebGLRenderingContext.actor.isShader;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isShader, "length", { value: 1 });
WebGLRenderingContext.prototype["isTexture"] = rsvm.browser.WebGLRenderingContext.actor.isTexture;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.isTexture, "length", { value: 1 });
WebGLRenderingContext.prototype["lineWidth"] = rsvm.browser.WebGLRenderingContext.actor.lineWidth;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.lineWidth, "length", { value: 1 });
WebGLRenderingContext.prototype["linkProgram"] = rsvm.browser.WebGLRenderingContext.actor.linkProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.linkProgram, "length", { value: 1 });
WebGLRenderingContext.prototype["pixelStorei"] = rsvm.browser.WebGLRenderingContext.actor.pixelStorei;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.pixelStorei, "length", { value: 2 });
WebGLRenderingContext.prototype["polygonOffset"] = rsvm.browser.WebGLRenderingContext.actor.polygonOffset;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.polygonOffset, "length", { value: 2 });
WebGLRenderingContext.prototype["readPixels"] = rsvm.browser.WebGLRenderingContext.actor.readPixels;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.readPixels, "length", { value: 7 });
WebGLRenderingContext.prototype["renderbufferStorage"] = rsvm.browser.WebGLRenderingContext.actor.renderbufferStorage;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.renderbufferStorage, "length", { value: 4 });
WebGLRenderingContext.prototype["sampleCoverage"] = rsvm.browser.WebGLRenderingContext.actor.sampleCoverage;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.sampleCoverage, "length", { value: 2 });
WebGLRenderingContext.prototype["shaderSource"] = rsvm.browser.WebGLRenderingContext.actor.shaderSource;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.shaderSource, "length", { value: 2 });
WebGLRenderingContext.prototype["stencilFunc"] = rsvm.browser.WebGLRenderingContext.actor.stencilFunc;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilFunc, "length", { value: 3 });
WebGLRenderingContext.prototype["stencilFuncSeparate"] = rsvm.browser.WebGLRenderingContext.actor.stencilFuncSeparate;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilFuncSeparate, "length", { value: 4 });
WebGLRenderingContext.prototype["stencilMask"] = rsvm.browser.WebGLRenderingContext.actor.stencilMask;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilMask, "length", { value: 1 });
WebGLRenderingContext.prototype["stencilMaskSeparate"] = rsvm.browser.WebGLRenderingContext.actor.stencilMaskSeparate;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilMaskSeparate, "length", { value: 2 });
WebGLRenderingContext.prototype["stencilOp"] = rsvm.browser.WebGLRenderingContext.actor.stencilOp;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilOp, "length", { value: 3 });
WebGLRenderingContext.prototype["stencilOpSeparate"] = rsvm.browser.WebGLRenderingContext.actor.stencilOpSeparate;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.stencilOpSeparate, "length", { value: 4 });
WebGLRenderingContext.prototype["texImage2D"] = rsvm.browser.WebGLRenderingContext.actor.texImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.texImage2D, "length", { value: 6 });
WebGLRenderingContext.prototype["texParameterf"] = rsvm.browser.WebGLRenderingContext.actor.texParameterf;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.texParameterf, "length", { value: 3 });
WebGLRenderingContext.prototype["texParameteri"] = rsvm.browser.WebGLRenderingContext.actor.texParameteri;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.texParameteri, "length", { value: 3 });
WebGLRenderingContext.prototype["texSubImage2D"] = rsvm.browser.WebGLRenderingContext.actor.texSubImage2D;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.texSubImage2D, "length", { value: 7 });
WebGLRenderingContext.prototype["useProgram"] = rsvm.browser.WebGLRenderingContext.actor.useProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.useProgram, "length", { value: 1 });
WebGLRenderingContext.prototype["validateProgram"] = rsvm.browser.WebGLRenderingContext.actor.validateProgram;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.validateProgram, "length", { value: 1 });
WebGLRenderingContext.prototype["bindBuffer"] = rsvm.browser.WebGLRenderingContext.actor.bindBuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bindBuffer, "length", { value: 2 });
WebGLRenderingContext.prototype["bindFramebuffer"] = rsvm.browser.WebGLRenderingContext.actor.bindFramebuffer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bindFramebuffer, "length", { value: 2 });
WebGLRenderingContext.prototype["bindTexture"] = rsvm.browser.WebGLRenderingContext.actor.bindTexture;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.bindTexture, "length", { value: 2 });
WebGLRenderingContext.prototype["clear"] = rsvm.browser.WebGLRenderingContext.actor.clear;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.clear, "length", { value: 1 });
WebGLRenderingContext.prototype["clearColor"] = rsvm.browser.WebGLRenderingContext.actor.clearColor;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.clearColor, "length", { value: 4 });
WebGLRenderingContext.prototype["clearDepth"] = rsvm.browser.WebGLRenderingContext.actor.clearDepth;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.clearDepth, "length", { value: 1 });
WebGLRenderingContext.prototype["clearStencil"] = rsvm.browser.WebGLRenderingContext.actor.clearStencil;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.clearStencil, "length", { value: 1 });
WebGLRenderingContext.prototype["colorMask"] = rsvm.browser.WebGLRenderingContext.actor.colorMask;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.colorMask, "length", { value: 4 });
WebGLRenderingContext.prototype["disableVertexAttribArray"] = rsvm.browser.WebGLRenderingContext.actor.disableVertexAttribArray;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.disableVertexAttribArray, "length", { value: 1 });
WebGLRenderingContext.prototype["drawArrays"] = rsvm.browser.WebGLRenderingContext.actor.drawArrays;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.drawArrays, "length", { value: 3 });
WebGLRenderingContext.prototype["drawElements"] = rsvm.browser.WebGLRenderingContext.actor.drawElements;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.drawElements, "length", { value: 4 });
WebGLRenderingContext.prototype["enableVertexAttribArray"] = rsvm.browser.WebGLRenderingContext.actor.enableVertexAttribArray;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.enableVertexAttribArray, "length", { value: 1 });
WebGLRenderingContext.prototype["scissor"] = rsvm.browser.WebGLRenderingContext.actor.scissor;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.scissor, "length", { value: 4 });
WebGLRenderingContext.prototype["uniform1f"] = rsvm.browser.WebGLRenderingContext.actor.uniform1f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform1f, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform1fv"] = rsvm.browser.WebGLRenderingContext.actor.uniform1fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform1fv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform1i"] = rsvm.browser.WebGLRenderingContext.actor.uniform1i;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform1i, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform1iv"] = rsvm.browser.WebGLRenderingContext.actor.uniform1iv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform1iv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform2f"] = rsvm.browser.WebGLRenderingContext.actor.uniform2f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform2f, "length", { value: 3 });
WebGLRenderingContext.prototype["uniform2fv"] = rsvm.browser.WebGLRenderingContext.actor.uniform2fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform2fv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform2i"] = rsvm.browser.WebGLRenderingContext.actor.uniform2i;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform2i, "length", { value: 3 });
WebGLRenderingContext.prototype["uniform2iv"] = rsvm.browser.WebGLRenderingContext.actor.uniform2iv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform2iv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform3f"] = rsvm.browser.WebGLRenderingContext.actor.uniform3f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform3f, "length", { value: 4 });
WebGLRenderingContext.prototype["uniform3fv"] = rsvm.browser.WebGLRenderingContext.actor.uniform3fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform3fv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform3i"] = rsvm.browser.WebGLRenderingContext.actor.uniform3i;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform3i, "length", { value: 4 });
WebGLRenderingContext.prototype["uniform3iv"] = rsvm.browser.WebGLRenderingContext.actor.uniform3iv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform3iv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform4f"] = rsvm.browser.WebGLRenderingContext.actor.uniform4f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform4f, "length", { value: 5 });
WebGLRenderingContext.prototype["uniform4fv"] = rsvm.browser.WebGLRenderingContext.actor.uniform4fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform4fv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniform4i"] = rsvm.browser.WebGLRenderingContext.actor.uniform4i;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform4i, "length", { value: 5 });
WebGLRenderingContext.prototype["uniform4iv"] = rsvm.browser.WebGLRenderingContext.actor.uniform4iv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniform4iv, "length", { value: 2 });
WebGLRenderingContext.prototype["uniformMatrix2fv"] = rsvm.browser.WebGLRenderingContext.actor.uniformMatrix2fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniformMatrix2fv, "length", { value: 3 });
WebGLRenderingContext.prototype["uniformMatrix3fv"] = rsvm.browser.WebGLRenderingContext.actor.uniformMatrix3fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniformMatrix3fv, "length", { value: 3 });
WebGLRenderingContext.prototype["uniformMatrix4fv"] = rsvm.browser.WebGLRenderingContext.actor.uniformMatrix4fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.uniformMatrix4fv, "length", { value: 3 });
WebGLRenderingContext.prototype["vertexAttrib1f"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib1f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib1f, "length", { value: 2 });
WebGLRenderingContext.prototype["vertexAttrib1fv"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib1fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib1fv, "length", { value: 2 });
WebGLRenderingContext.prototype["vertexAttrib2f"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib2f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib2f, "length", { value: 3 });
WebGLRenderingContext.prototype["vertexAttrib2fv"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib2fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib2fv, "length", { value: 2 });
WebGLRenderingContext.prototype["vertexAttrib3f"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib3f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib3f, "length", { value: 4 });
WebGLRenderingContext.prototype["vertexAttrib3fv"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib3fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib3fv, "length", { value: 2 });
WebGLRenderingContext.prototype["vertexAttrib4f"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib4f;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib4f, "length", { value: 5 });
WebGLRenderingContext.prototype["vertexAttrib4fv"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttrib4fv;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttrib4fv, "length", { value: 2 });
WebGLRenderingContext.prototype["vertexAttribPointer"] = rsvm.browser.WebGLRenderingContext.actor.vertexAttribPointer;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.vertexAttribPointer, "length", { value: 6 });
WebGLRenderingContext.prototype["viewport"] = rsvm.browser.WebGLRenderingContext.actor.viewport;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.viewport, "length", { value: 4 });
WebGLRenderingContext.prototype["makeXRCompatible"] = rsvm.browser.WebGLRenderingContext.actor.makeXRCompatible;
Object.defineProperty(rsvm.browser.WebGLRenderingContext.actor.makeXRCompatible, "length", { value: 0 });


Object.defineProperty(WebGLRenderingContext.prototype, "canvas", {
    get: rsvm.browser.WebGLRenderingContext.getter.canvas,
    configurable: true, enumerable: true,
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.getter.canvas, "name", {
    value: "get canvas"
});
Object.defineProperty(WebGLRenderingContext.prototype, "drawingBufferWidth", {
    get: rsvm.browser.WebGLRenderingContext.getter.drawingBufferWidth,
    configurable: true, enumerable: true,
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.getter.drawingBufferWidth, "name", {
    value: "get drawingBufferWidth"
});
Object.defineProperty(WebGLRenderingContext.prototype, "drawingBufferHeight", {
    get: rsvm.browser.WebGLRenderingContext.getter.drawingBufferHeight,
    configurable: true, enumerable: true,
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.getter.drawingBufferHeight, "name", {
    value: "get drawingBufferHeight"
});
Object.defineProperty(WebGLRenderingContext.prototype, "drawingBufferColorSpace", {
    get: rsvm.browser.WebGLRenderingContext.getter.drawingBufferColorSpace,
    set: rsvm.browser.WebGLRenderingContext.setter.drawingBufferColorSpace,
    configurable: true, enumerable: true,
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.getter.drawingBufferColorSpace, "name", {
    value: "get drawingBufferColorSpace"
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.setter.drawingBufferColorSpace, "length", {
    value: 1
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.setter.drawingBufferColorSpace, "name", {
    value: "set drawingBufferColorSpace"
});
Object.defineProperty(WebGLRenderingContext.prototype, "unpackColorSpace", {
    get: rsvm.browser.WebGLRenderingContext.getter.unpackColorSpace,
    set: rsvm.browser.WebGLRenderingContext.setter.unpackColorSpace,
    configurable: true, enumerable: true,
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.getter.unpackColorSpace, "name", {
    value: "get unpackColorSpace"
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.setter.unpackColorSpace, "length", {
    value: 1
});
Object.defineProperty(rsvm.browser.WebGLRenderingContext.setter.unpackColorSpace, "name", {
    value: "set unpackColorSpace"
});


for (const key in rsvm.browser.WebGLRenderingContext.getter) {
    rsvm.safefunction(rsvm.browser.WebGLRenderingContext.getter[key]);
}
for (const key in rsvm.browser.WebGLRenderingContext.setter) {
    rsvm.safefunction(rsvm.browser.WebGLRenderingContext.setter[key]);
}
for (const key in rsvm.browser.WebGLRenderingContext.actor) {
    rsvm.safefunction(rsvm.browser.WebGLRenderingContext.actor[key]);
};


WebGLRenderingContext = rsvm.proxy(WebGLRenderingContext);