CREATE TABLE meinv(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    src VARCHAR(200) NOT NULL
);
ALTER TABLE meinv
ADD local_path VARCHAR(100);
TRUNCATE TABLE meinv;